version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "2345:5432"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
